package me.jass.practice.datatypes;

public enum Goal {
	CREATE_ARENA, CREATE_EXTRA, CREATE_KIT, EDIT_LAYOUT, EDIT_ARENA, EDIT_KIT, EDIT_EXTRA, DUEL, CHALLENGE, CASUAL_QUEUE, COMPETITIVE_QUEUE, SPECTATE, VIEW, STATS, LEADERBOARDS
}