package me.jass.practice.datatypes;

public enum GUI {
	LAYOUT_EDITOR, KITS, ARENAS, KIT_EDITOR, ARENA_EDITOR, EXTRA_EDITOR, ROUNDS, SETTINGS, SCORES, AVAILABLE_PLAYERS, UNAVAILABLE_PLAYERS, QUEUES, CHALLENGE, CASUAL_KITS, CASUAL_ARENAS,
	COMPETITIVE_KITS, COMPETITIVE_ARENAS, EXTRAS, VIEWS
}